#!/usr/bin/env python3
"""Generate the `mcp-tools` skill from docs/runbooks/mcp-tools.md.

Single source of truth = `docs/runbooks/mcp-tools.md`, the maintainer reference. That runbook is
unreadable to a *wire-connected* agent (it lives in the repo, not on the MCP wire), so this script
projects it into a progressive-disclosure skill such an agent CAN consume: a lean router
`SKILL.md` that indexes every tool, plus one leaf `reference/tools/<name>.md` per tool and a couple
of cross-tool prose files. Loading the router costs a table; loading one tool costs one small file.

Everything under `skills/mcp-tools/` is GENERATED — never hand-edit it. Edit the runbook and rerun
`python3 scripts/generate.py`. `--check` regenerates into a scratch dir and diffs (CI / pre-commit
fail on drift), mirroring the repo's proto-freshness gate. Python 3 stdlib only (plugin policy).

Usage:
  python3 scripts/generate.py            # (re)write the skill from the runbook
  python3 scripts/generate.py --check    # exit 1 if the committed skill is stale vs the runbook
  python3 scripts/generate.py --self-test
"""

import argparse
import re
import sys
import tempfile
from pathlib import Path

# scripts/ -> mcp-tools-docs/ -> plugins/ -> repo root
REPO_ROOT = Path(__file__).resolve().parents[3]
SOURCE_REL = "docs/runbooks/mcp-tools.md"
SKILL_REL = "plugins/mcp-tools-docs/skills/mcp-tools"

# H2 sections whose H3 subsections are individual tools (everything else is cross-tool prose).
TOOL_SECTIONS = {"Tools", "Database Tools (Admin-only)"}
BANNER = "<!-- GENERATED by plugins/mcp-tools-docs/scripts/generate.py from docs/runbooks/mcp-tools.md — DO NOT EDIT. Edit the runbook and regenerate. -->"

H2_RE = re.compile(r"^## (?P<title>.+?)\s*$")
H3_RE = re.compile(r"^### (?P<title>.+?)\s*$")


def _strip_ticks(title):
    return title.strip().strip("`").strip()


def parse(md_text):
    """Return (h1_title, sections) where sections is an ordered list of dicts.

    Each section: {title, is_tools, prose_lines, tools:[{name, body_lines}]}. Trailing `---`
    horizontal rules and blank padding are trimmed from every captured block so the projection is
    stable regardless of the runbook's separator spacing.
    """
    lines = md_text.splitlines()
    h1 = next((ln[2:].strip() for ln in lines if ln.startswith("# ")), "MCP Tools")

    sections = []
    cur = None      # current H2 section
    cur_tool = None  # current H3 tool within a tools section

    def flush_tool():
        nonlocal cur_tool
        if cur_tool is not None:
            cur_tool["body_lines"] = _trim(cur_tool["body_lines"])
            cur["tools"].append(cur_tool)
            cur_tool = None

    for ln in lines:
        h2 = H2_RE.match(ln)
        if h2:
            flush_tool()
            if cur is not None:
                cur["prose_lines"] = _trim(cur["prose_lines"])
                sections.append(cur)
            title = h2.group("title")
            cur = {"title": title, "is_tools": title in TOOL_SECTIONS,
                   "prose_lines": [], "tools": []}
            continue
        if cur is None:
            continue  # preamble before the first H2 (the H1 + intro) — not projected
        if cur["is_tools"]:
            h3 = H3_RE.match(ln)
            if h3:
                flush_tool()
                cur_tool = {"name": _strip_ticks(h3.group("title")), "body_lines": []}
                continue
            if cur_tool is not None:
                cur_tool["body_lines"].append(ln)
            # lines before the first tool H3 (section preamble) are kept as section prose
            elif ln.strip() and ln.strip() != "---":
                cur["prose_lines"].append(ln)
        else:
            cur["prose_lines"].append(ln)

    flush_tool()
    if cur is not None:
        cur["prose_lines"] = _trim(cur["prose_lines"])
        sections.append(cur)
    return h1, sections


def _trim(block_lines):
    """Drop leading/trailing blank lines and a trailing `---` rule."""
    out = list(block_lines)
    while out and not out[0].strip():
        out.pop(0)
    while out and (not out[-1].strip() or out[-1].strip() == "---"):
        out.pop()
    return out


def one_liner(body_lines, limit=160):
    """First prose sentence of a tool body — skips blank/table/blockquote/bold-directive lines."""
    for ln in body_lines:
        s = ln.strip()
        if not s or s.startswith(("|", ">", "#", "-", "*", "```")):
            continue
        # first sentence: up to a '. ' that is not inside inline code / a decimal
        m = re.search(r"\.(?:\s|$)", s)
        text = s[: m.start() + 1] if m else s
        if len(text) > limit:
            text = text[: limit - 1].rstrip() + "…"
        return text
    return ""


def render(h1, sections):
    """Return {relative_path_under_skill_dir: file_text}. Deterministic."""
    files = {}

    prose = {s["title"]: s for s in sections if not s["is_tools"]}

    def prose_block(*titles):
        chunks = []
        for t in titles:
            s = prose.get(t)
            if s and s["prose_lines"]:
                chunks.append(f"## {t}\n\n" + "\n".join(s["prose_lines"]))
        return "\n\n".join(chunks)

    transport_auth = prose_block("Transport Modes", "Authentication")
    if transport_auth:
        files["reference/transport-auth.md"] = (
            f"{BANNER}\n\n# Transport & authentication\n\n"
            "How a client connects to the xstockstrat-agent MCP server and authenticates.\n\n"
            f"{transport_auth}\n"
        )

    usage = prose_block("Usage Patterns", "Config Keys")
    if usage:
        files["reference/usage-patterns.md"] = (
            f"{BANNER}\n\n# Cross-tool usage patterns & config keys\n\n"
            "Multi-tool workflows and the config keys that govern tool behavior.\n\n"
            f"{usage}\n"
        )

    # Per-tool leaf files + the router's index rows, in document order.
    index_groups = []  # (group_heading, [(name, one_liner)])
    for s in sections:
        if not s["is_tools"]:
            continue
        rows = []
        for tool in s["tools"]:
            name = tool["name"]
            body = "\n".join(tool["body_lines"])
            files[f"reference/tools/{name}.md"] = (
                f"{BANNER}\n\n# `{name}`\n\n{body}\n"
            )
            rows.append((name, one_liner(tool["body_lines"])))
        index_groups.append((s["title"], rows))

    files["SKILL.md"] = render_router(h1, index_groups, bool(transport_auth), bool(usage))
    return files


def render_router(h1, index_groups, has_transport, has_usage):
    total = sum(len(rows) for _, rows in index_groups)
    desc = (
        f"Reference documentation for the {total} MCP tools exposed by the xstockstrat-agent MCP "
        "server (signal ingestion, backtesting, strategy/formula management, config, alerts, "
        "watchlists, accounts, user admin, and admin-only database tools). Use this when a "
        "wire-connected agent needs a tool's parameters, return shape, error cases, or "
        "cross-tool usage patterns and cannot read the repo's maintainer runbook. Each tool has "
        "its own reference file so only the one in play is loaded."
    )
    lines = [
        "---",
        "name: mcp-tools",
        f"description: {desc}",
        "allowed-tools: Read",
        "---",
        "",
        BANNER,
        "",
        f"# {h1}",
        "",
        "This skill projects the maintainer runbook (`docs/runbooks/mcp-tools.md`) into a form a "
        "**wire-connected agent can consume**. Load only what you need:",
        "",
    ]
    if has_transport:
        lines.append("- **Connecting / auth** → `reference/transport-auth.md`")
    if has_usage:
        lines.append("- **Cross-tool workflows & config keys** → `reference/usage-patterns.md`")
    lines += [
        "- **A specific tool** → find it below and open its `reference/tools/<name>.md`.",
        "",
        "Do not read every reference file up front — open one tool file at a time.",
        "",
    ]
    for heading, rows in index_groups:
        lines.append(f"## {heading}")
        lines.append("")
        lines.append("| Tool | Summary | Reference |")
        lines.append("|---|---|---|")
        for name, summary in rows:
            summary = summary.replace("|", "\\|")
            lines.append(f"| `{name}` | {summary} | `reference/tools/{name}.md` |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_files(skill_dir, files):
    # Clean the generated tree so a removed tool leaves no orphan file, then rewrite.
    tools_dir = skill_dir / "reference" / "tools"
    if tools_dir.is_dir():
        for f in tools_dir.glob("*.md"):
            f.unlink()
    for rel, text in files.items():
        dst = skill_dir / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(text, encoding="utf-8")


def current_files(skill_dir):
    out = {}
    for f in skill_dir.rglob("*.md"):
        out[str(f.relative_to(skill_dir))] = f.read_text(encoding="utf-8")
    return out


def generate(source_path, skill_dir):
    h1, sections = parse(source_path.read_text(encoding="utf-8"))
    return render(h1, sections)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if committed skill is stale")
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--source", type=Path, default=REPO_ROOT / SOURCE_REL)
    ap.add_argument("--skill-dir", type=Path, default=REPO_ROOT / SKILL_REL)
    args = ap.parse_args()

    if args.self_test:
        return self_test()

    if not args.source.is_file():
        print(f"ERROR: source runbook not found: {args.source}")
        return 1

    files = generate(args.source, args.skill_dir)

    if args.check:
        have = current_files(args.skill_dir)
        want = files
        stale = sorted(set(have) | set(want))
        drift = [p for p in stale if have.get(p) != want.get(p)]
        if drift:
            print("DRIFT: the committed mcp-tools skill is stale vs docs/runbooks/mcp-tools.md.")
            for p in drift:
                if p not in have:
                    print(f"  missing (regenerate): {p}")
                elif p not in want:
                    print(f"  orphan (regenerate):  {p}")
                else:
                    print(f"  changed (regenerate): {p}")
            print("Run: python3 plugins/mcp-tools-docs/scripts/generate.py")
            return 1
        print(f"OK: mcp-tools skill matches {SOURCE_REL} ({len(want)} files)")
        return 0

    write_files(args.skill_dir, files)
    print(f"OK: wrote {len(files)} files to {args.skill_dir} from {args.source}")
    return 0


def self_test():
    sample = """# MCP Tools Reference — test-agent

## Transport Modes

stdio and http.

## Tools

### `alpha_tool`

Does the alpha thing. Second sentence ignored.

**Parameters**

| p | t |
|---|---|
| x | int |

---

### `beta_tool`

Beta summary here.

## Database Tools (Admin-only)

Preamble about db tools.

### db_ping

Pings the database.

**Returns**: pong.
"""
    failures = []
    with tempfile.TemporaryDirectory() as tmp:
        src = Path(tmp) / "mcp-tools.md"
        src.write_text(sample, encoding="utf-8")
        skill = Path(tmp) / "skill"
        files = generate(src, skill)

        def want(cond, msg):
            if not cond:
                failures.append(msg)

        want("reference/tools/alpha_tool.md" in files, "alpha_tool file missing")
        want("reference/tools/beta_tool.md" in files, "beta_tool file missing")
        want("reference/tools/db_ping.md" in files, "db_ping (plain H3) file missing")
        want("reference/transport-auth.md" in files, "transport-auth prose missing")
        router = files["SKILL.md"]
        want("`alpha_tool`" in router and "reference/tools/alpha_tool.md" in router,
             "router does not index alpha_tool")
        want("Does the alpha thing." in router and "Second sentence ignored" not in router,
             "one-liner did not stop at first sentence")
        want("| `db_ping` |" in router, "db_ping not in router index")
        want("Parameters" in files["reference/tools/alpha_tool.md"],
             "tool body (Parameters table) not captured")
        # --check must be stable: writing then checking is clean
        write_files(skill, files)
        again = generate(src, skill)
        want(current_files(skill) == again, "generation is not idempotent")

    if failures:
        print("\n".join(f"self-test FAIL: {f}" for f in failures))
        return 1
    print("self-test: all assertions passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
