/**
 * Connect-RPC client for xstockstrat-config ConfigService.
 *
 * Used server-side in Next.js Route Handlers to proxy requests from the
 * config-ui browser client to the config service.
 */
import { createClient } from '@connectrpc/connect';
import { createNodeHttpTransport } from '@connectrpc/connect-node';

// CONFIG_ENDPOINT points to the Connect-RPC HTTP port (8060), not the gRPC port (50060)
const CONFIG_ENDPOINT =
  process.env.CONFIG_ENDPOINT ?? 'http://xstockstrat-config:8060';

const transport = createNodeHttpTransport({ baseUrl: CONFIG_ENDPOINT, httpVersion: '1.1' });

// ConfigService descriptor — generated by buf.build/connectrpc/es
// The type definition below is a lightweight placeholder matching the proto shape.
// Replace with the actual generated service definition from gen/ts once buf generate runs.
export const ConfigService = {
  typeName: 'xstockstrat.config.v1.ConfigService',
  methods: {
    getConfig: {
      name: 'GetConfig',
      I: {} as any,
      O: {} as any,
      kind: 'unary' as const,
    },
    setConfig: {
      name: 'SetConfig',
      I: {} as any,
      O: {} as any,
      kind: 'unary' as const,
    },
    listKeys: {
      name: 'ListKeys',
      I: {} as any,
      O: {} as any,
      kind: 'unary' as const,
    },
  },
} as const;

export const configClient = createClient(ConfigService as any, transport);
