name: Deploy prod

on:
  push:
    branches:
      - main

jobs:
  buf-push:
    name: Publish proto definitions to BSR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: bufbuild/buf-push-action@v1
        with:
          input: packages/proto
          buf_token: ${{ secrets.BUF_TOKEN }}

  deploy:
    name: Deploy to prod
    uses: ./.github/workflows/deploy.yml
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      DO_APP_ID: ${{ secrets.DO_PROD_APP_ID }}
    with:
      app_spec: .do/app.yaml
